---
# This playbook will install Apache Web Server with php and mysql support
- name: linux_deploy_nginx
  hosts: all
  tasks:
  - name: Install Nginx
    apt:
      name: "{{ item }}"
      state: latest
    loop:
     - nginx
    when: ansible_os_family == "Debian"

  - name: Setting default HTTP Server page
    shell: echo "<h1>welcome to Miztiik Ansible Playbook Demo</h1>" >> /var/www/html/index.html

  - name: Start nginx Webserver
    service:
      name: nginx
      state: restarted

  - name: enable apache on startup and start service for redhat or centos
    service: name=nginx enabled=yes state=started
    when: ansible_os_family == "Debian"
